#### NumPy program to create an array of all even integers from 30 to 70.



In [1]:
import numpy as np
even_arr = np.arange(30, 71, 2)
print(even_arr)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


####  NumPy program to generate an array of 15 random numbers from a standard normal distribution.


In [4]:
import numpy as np
rndm_arr = np.random.randn(15)
print(rndm_arr)


[-2.15041579  1.12312375 -0.82011768  1.02717148  1.90655279  0.39082727
  0.08821119  0.06127325 -1.2706435  -0.9443814   0.09100636  0.60410915
 -0.67223878  0.56572513  0.81699515]


#### Cross-product of two matrices in NumPy.

Cross product does not exist in matrices.

#### Determinant of an array using NumPy.

In [9]:
import numpy as np
a = np.array([[1, 2], [1, 2]])
determinant = np.linalg.det(a)
print("Determinant of the array is:")
print(determinant)


Determinant of the array is:
0.0


#### Create a 3x3x3 array with random values using NumPy.

In [8]:
import numpy as np
rand_3d_array = np.random.rand(3, 3, 3)
print(rand_3d_array)


[[[0.40073921 0.03513492 0.41363785]
  [0.72424736 0.60040061 0.96453728]
  [0.85488887 0.83604093 0.01642988]]

 [[0.47413269 0.25414091 0.66513417]
  [0.76672779 0.67099213 0.02397116]
  [0.14630396 0.86107877 0.66746465]]

 [[0.72060292 0.16732855 0.07312606]
  [0.55546146 0.34713969 0.73768744]
  [0.68490231 0.32504876 0.66765722]]]


####  Create a 5x5 array with random values and find the minimum and maximum values using NumPy.

In [12]:
import numpy as np
random_5x5_array = np.random.rand(5, 5)
min_val = np.min(random_5x5_array)
max_val = np.max(random_5x5_array)

print(random_5x5_array)
print("\nMinimum value is:", min_val)
print("Maximum value is:", max_val)


[[0.66717547 0.89893795 0.34824509 0.15051528 0.99980988]
 [0.29251535 0.05650452 0.48215234 0.80905132 0.50145594]
 [0.03279808 0.67871949 0.88535078 0.62866184 0.11270063]
 [0.99020858 0.43594506 0.10554616 0.97280028 0.85599711]
 [0.05409464 0.22665102 0.39540856 0.54979314 0.91552781]]

Minimum value is: 0.032798084373017566
Maximum value is: 0.999809876760772


####  Mean, standard deviation, and variance of a given array along the second axis in NumPy.

In [13]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

mean = np.mean(arr, axis=1)
dev = np.std(arr, axis=1)
variance = np.var(arr, axis=1)

print("Mean along the second axis is:", mean)
print("Standard deviation along the second axis is :", dev)
print("Variance along the second axis is :", variance)


Mean along the second axis is: [2. 5. 8.]
Standard deviation along the second axis is : [0.81649658 0.81649658 0.81649658]
Variance along the second axis is : [0.66666667 0.66666667 0.66666667]
